# Generated by Django 4.0 on 2022-05-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('clas', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('more', models.BooleanField(default=False)),
            ],
        ),
    ]
