# Generated by Django 4.0 on 2022-05-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajeet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='contract',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
