# Generated by Django 4.0 on 2022-05-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajeet', '0002_destination_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='contract',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
